//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GroMartDBEntities : DbContext
    {
        public GroMartDBEntities()
            : base("name=GroMartDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MSTR_DELIVERY_STATUS> MSTR_DELIVERY_STATUS { get; set; }
        public virtual DbSet<MSTR_PINCODE> MSTR_PINCODE { get; set; }
        public virtual DbSet<MSTR_PLACE> MSTR_PLACE { get; set; }
        public virtual DbSet<MSTR_PRODUCT> MSTR_PRODUCT { get; set; }
        public virtual DbSet<MSTR_USER_ROLE> MSTR_USER_ROLE { get; set; }
        public virtual DbSet<TRN_COUSTOMER_ORDER_DETAILS> TRN_COUSTOMER_ORDER_DETAILS { get; set; }
        public virtual DbSet<TRN_DELIVERY_ADDRESS_DETAILS> TRN_DELIVERY_ADDRESS_DETAILS { get; set; }
        public virtual DbSet<TRN_ORDER_LOG> TRN_ORDER_LOG { get; set; }
        public virtual DbSet<TRN_USERDETAILS> TRN_USERDETAILS { get; set; }
    }
}
