//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTR_PINCODE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSTR_PINCODE()
        {
            this.MSTR_PLACE = new HashSet<MSTR_PLACE>();
            this.TRN_DELIVERY_ADDRESS_DETAILS = new HashSet<TRN_DELIVERY_ADDRESS_DETAILS>();
        }
    
        public string PINCODE_ID { get; set; }
        public string PINCODE_NO { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_ON { get; set; }
        public bool ISACTIVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSTR_PLACE> MSTR_PLACE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_DELIVERY_ADDRESS_DETAILS> TRN_DELIVERY_ADDRESS_DETAILS { get; set; }
    }
}
