//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTR_DELIVERY_STATUS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSTR_DELIVERY_STATUS()
        {
            this.TRN_ORDER_LOG = new HashSet<TRN_ORDER_LOG>();
        }
    
        public string STATUS_ID { get; set; }
        public string STATUS_NAME { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime UPDATED_ON { get; set; }
        public string UPDATED_BY { get; set; }
        public bool ISACTIVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_ORDER_LOG> TRN_ORDER_LOG { get; set; }
    }
}
