//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTR_PLACE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSTR_PLACE()
        {
            this.TRN_DELIVERY_ADDRESS_DETAILS = new HashSet<TRN_DELIVERY_ADDRESS_DETAILS>();
        }
    
        public string PLACE_ID { get; set; }
        public string REF_PINCODE_ID { get; set; }
        public string PLACE_NAME { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_ON { get; set; }
        public bool ISACTIVE { get; set; }
    
        public virtual MSTR_PINCODE MSTR_PINCODE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_DELIVERY_ADDRESS_DETAILS> TRN_DELIVERY_ADDRESS_DETAILS { get; set; }
    }
}
