//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_ORDER_LOG
    {
        public string ORDER_LOG_ID { get; set; }
        public string REF_DELIVERY_ID { get; set; }
        public string REF_STATUS_ID { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public bool ISACTIVE { get; set; }
    
        public virtual MSTR_DELIVERY_STATUS MSTR_DELIVERY_STATUS { get; set; }
        public virtual TRN_DELIVERY_ADDRESS_DETAILS TRN_DELIVERY_ADDRESS_DETAILS { get; set; }
    }
}
