//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_USERDETAILS
    {
        public string USER_ID { get; set; }
        public string FULL_NAME { get; set; }
        public string EMAIL_ID { get; set; }
        public string PHONE_NO { get; set; }
        public string PASSWORD { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_ON { get; set; }
        public bool ISACTIVE { get; set; }
        public string REF_ROLE_ID { get; set; }
    
        public virtual MSTR_USER_ROLE MSTR_USER_ROLE { get; set; }
    }
}
