//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_DELIVERY_ADDRESS_DETAILS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRN_DELIVERY_ADDRESS_DETAILS()
        {
            this.TRN_COUSTOMER_ORDER_DETAILS = new HashSet<TRN_COUSTOMER_ORDER_DETAILS>();
            this.TRN_ORDER_LOG = new HashSet<TRN_ORDER_LOG>();
        }
    
        public string DELIVERY_ID { get; set; }
        public string NAME { get; set; }
        public string DELIVERY_ADDRESS { get; set; }
        public string LANDMARK { get; set; }
        public string REF_PINCODE_ID { get; set; }
        public string REF_PLACE_ID { get; set; }
        public string MOBILE_NO { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public bool ISACTIVE { get; set; }
    
        public virtual MSTR_PINCODE MSTR_PINCODE { get; set; }
        public virtual MSTR_PLACE MSTR_PLACE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_COUSTOMER_ORDER_DETAILS> TRN_COUSTOMER_ORDER_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_ORDER_LOG> TRN_ORDER_LOG { get; set; }
    }
}
